### ISSUE TITLE
poetry install not working on MacOS

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/cryptol#1491]
On MacOS, I cannot get `poetry install` to work in either the `saw-remote-api` directory or the `cryptol-remote-api` directory. The reason is that typed-ast (1.4.3) builds with errors.

```
ast3/Python/ast.c:4514:9: error: implicit declaration of function '_PyUnicode_DecodeUnicodeEscape' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
            v = _PyUnicode_DecodeUnicodeEscape(s, len, NULL, &first_invalid_escape);
```

Any help would be appreciated.

**Comment by RyanGlScott** [comment]
Unfortunately, the `typed-ast` package simply does not build with Python 3.11+. A workaround is to downgrade to an older version of Python, but clearly that is not sustainable long-term.

Given that `typed-ast` is being [end-of-life](https://github.com/python/typed_ast/issues/179)'d soon, we really should look into getting rid of this dependency. That being said, I'm not sure (from a quick glance) what is incurring this dependency, as we aren't directly depending on it in `argo` or `cryptol-remote-api`.

**Comment by RyanGlScott** [comment]
Ah, the `typed-ast` dependency is coming from `mypy`. Specifically, it's for `mypy` + Python 3.7 or earlier, as those versions of Python lacked certain capabilities than `mypy` needs. If I understand things correctly, then we should be able to drop the `typed-ast` dependency by simply upgrading the `mypy` version. I'll give that a try.

**Comment by RyanGlScott** [comment]
@weaversa, do you mind checking out GaloisInc/argo#195 (i.e., the [`cryptol-T1491`](https://github.com/GaloisInc/argo/tree/cryptol-T1491) branch of `argo`) and seeing if you can successfully run the following:

```
$ cd python
$ python update
$ python install
```

If so, that is a pretty good sign that the underlying issue has been fixed.

**Comment by weaversa** [comment]
`poetry install` worked!

**Comment by RyanGlScott** [comment]
I've released a new `argo-client`  PyPI release with these changes [here](https://pypi.org/project/argo-client/0.0.11/). #1493 makes corresponding changes on the `cryptol-remote-api` side.

**Comment by weaversa** [comment]
> I've released a new `argo-client` PyPI release with these changes [here](https://pypi.org/project/argo-client/0.0.11/). #1493 makes corresponding changes on the `cryptol-remote-api` side.

Thanks! Would you mind seeing that these changes are propagated to `saw-remote-api` as well (I think the python client there is so old it uses the cryptol-remote-api 2.12 version).

**Comment by RyanGlScott** [comment]
Yes, definitely. See GaloisInc/saw-script#1809.
