### ISSUE TITLE
Can't compile with GHC 8.4.1

### ISSUE THREAD

**Issue by LeventErkok** [GaloisInc/cryptol#501]
Lots of things fail, but mostly due to Prelude now exporting `<>`:

```
src/Data/Integer/SAT.hs:680:25: error:
    Precedence parsing error
        cannot mix ‘<+>’ [infixl 6] and ‘Prelude.<>’ [infixr 6] in the same infix expression
    |
680 |   node x d            = integer x <+> brackets (text "label=" <> text (show d))
    |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
```

This is while compiling the `presburger` dependence. I wouldn't be surprised there were a ton of others like this elsewhere too.

**Comment by ilovezfs** [comment]
`presburger` has been fixed in master. The next error is with smtLib. That, too, has been fixed in master.

See https://github.com/yav/presburger/pull/7 and https://github.com/yav/smtLib/pull/6.

Once those patches are applied, however, cryptol itself fails to build with the following error:
```
Building library for cryptol-2.5.0..
[ 6 of 87] Compiling Cryptol.Utils.PP ( src/Cryptol/Utils/PP.hs, dist/dist-sandbox-11f9ca41/build/Cryptol/Utils/PP.o )

src/Cryptol/Utils/PP.hs:174:27: error:
    Ambiguous occurrence ‘<>’
    It could refer to either ‘Prelude.Compat.<>’,
                             imported from ‘Prelude.Compat’ at src/Cryptol/Utils/PP.hs:26:1-21
                             (and originally defined in ‘GHC.Base’)
                          or ‘Cryptol.Utils.PP.<>’,
                             defined at src/Cryptol/Utils/PP.hs:208:1
    |
174 | ordinal x = text (show x) <> text (ordSuffix x)
    |                           ^^

src/Cryptol/Utils/PP.hs:255:29: error:
    Ambiguous occurrence ‘<>’
    It could refer to either ‘Prelude.Compat.<>’,
                             imported from ‘Prelude.Compat’ at src/Cryptol/Utils/PP.hs:26:1-21
                             (and originally defined in ‘GHC.Base’)
                          or ‘Cryptol.Utils.PP.<>’,
                             defined at src/Cryptol/Utils/PP.hs:208:1
    |
255 |             | otherwise = d <> p : go ds
    |                             ^^
Failed to install cryptol-2.5.0
cabal: Error: some packages failed to install:
cryptol-2.5.0-GxmsH7ShXIZ7QUrUtmTnUR failed during the building phase. The
exception was:
ExitFailure 1
bash-3.2$ 
```

**Comment by atomb** [comment]
I'm working through these, one by one, and should have it building with 8.4 soon.

**Comment by ilovezfs** [comment]
Awesome! Thanks @atomb :)

**Comment by atomb** [comment]
I think Cryptol should build with 8.4 now. I've only tested it as a dependency of `saw-script` (which still needs updates to some other dependencies before it'll fully build with 8.4), but it seemed to work.

**Comment by yav** [comment]
This seems to work now.

**Comment by ilovezfs** [comment]
@yav yep HEAD builds fine with GHC 8.4.x, assuming we also use presburger HEAD. Any chance of getting a new release of both of them?

**Comment by atomb** [comment]
Cryptol doesn't depend on `presburger` anymore. For a while, it was still listed in the dependencies, and the Cabal/Stack package freeze files, but it's been removed from those, too.

**Comment by ilovezfs** [comment]
@atomb thanks for pointing that out!

In any case a GHC 8.4.x compatible release of cryptol would be appreciated.
