### ISSUE TITLE
Can't install cryptol from hackage using GHC 8.10.1

### ISSUE THREAD

**Issue by LeventErkok** [GaloisInc/cryptol#847]
I've:

```
$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.10.1
$ cabal --version
cabal-install version 3.2.0.0
compiled using version 3.2.0.0 of the Cabal library
```

`cabal new-install cryptol` eventually dies with:

```
...
[20 of 90] Compiling Cryptol.Parser.Names ( src/Cryptol/Parser/Names.hs, dist/build/Cryptol/Parser/Names.o, dist/build/Cryptol/Parser/Names.dyn_o )
[21 of 90] Compiling Cryptol.Parser.NoPat ( src/Cryptol/Parser/NoPat.hs, dist/build/Cryptol/Parser/NoPat.o, dist/build/Cryptol/Parser/NoPat.dyn_o )

src/Cryptol/Parser/NoPat.hs:545:3: error:
    ‘fail’ is not a (visible) method of class ‘Monad’
    |
545 |   fail x    = M (fail x)
    |   ^^^^
cabal: Failed to build cryptol-2.8.0 (which is required by exe:cryptol from
cryptol-2.8.0 and exe:cryptol-html from cryptol-2.8.0). See the build log
above for details.
```

**Comment by yav** [comment]
We just released 2.9, which should work with 8.10.1, could you give that a go?  This just happened yesterday evening, so you may have to do a `cabal update`.

**Comment by LeventErkok** [comment]
Works!
